"""initial migration

Revision ID: 2a0745633da5
Revises: None
Create Date: 2014-06-07 20:18:17.632111

"""

# revision identifiers, used by Alembic.
revision = '2a0745633da5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_password'), 'registros', ['password'], unique=False)
    op.create_index(op.f('ix_registros_usuario'), 'registros', ['usuario'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_usuario'), table_name='registros')
    op.drop_index(op.f('ix_registros_password'), table_name='registros')
    op.drop_table('registros')
    ### end Alembic commands ###
